# Generated by Django 5.1 on 2024-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default=47897802963480, max_length=15),
            preserve_default=False,
        ),
    ]
