# Generated by Django 5.1 on 2024-08-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
